language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
os:
    - linux
install: "pip install -r dev-requirements.txt"
script: "coverage run --source=./prwlock setup.py test"
after_success:
    - coveralls
